#@ load("@ytt:data", "data")
---
apiVersion: service-registry.spring.apps.tanzu.vmware.com/v1alpha1
kind: EurekaServer
metadata:
  name: #@ data.values.springCloudServices.registryName
  namespace: #@ data.values.serviceNamespace
  labels:
    services.apps.tanzu.vmware.com/class: #@ data.values.springCloudServices.registryName
spec:
  replicas: 1
  tls:
    activated: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eureka-app-operator-reader
  labels:
    servicebinding.io/controller: "true"
rules:
- apiGroups: ["service-registry.spring.apps.tanzu.vmware.com"]
  resources: ["eurekaservers"]
  verbs: ["get", "list", "watch"]
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: #@ data.values.springCloudServices.registryName
spec:
  description:
    short: Where For Dinner Registry Server Instances
  pool:
    group: service-registry.spring.apps.tanzu.vmware.com
    kind: EurekaServer  
    labelSelector:
      matchLabels:
        services.apps.tanzu.vmware.com/class: #@ data.values.springCloudServices.registryName

